// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcloCY7tybl_SKuR9JSAV5LKR9CmhLMoE',
    appId: '1:1030615923239:web:05d27b8e72be295e3b2c02',
    messagingSenderId: '1030615923239',
    projectId: 'documentrecovery-307a4',
    authDomain: 'documentrecovery-307a4.firebaseapp.com',
    storageBucket: 'documentrecovery-307a4.firebasestorage.app',
    measurementId: 'G-1RMME8P7DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYzzciA2-TlMDP3P-fc6q8QfuqH0OLSCk',
    appId: '1:1030615923239:android:2e995cb7249ec5643b2c02',
    messagingSenderId: '1030615923239',
    projectId: 'documentrecovery-307a4',
    storageBucket: 'documentrecovery-307a4.firebasestorage.app',
  );
}
